--- 
- name: roles test     
  gather_facts: no
  hosts: all
  remote_user: root

  roles:
     #- db 
     - php
- name: install apache
  gather_facts: no
  hosts: web1
  remote_user: root
  

  roles:
     - httpd
       
