---
- name: install mysql-server mysql-client
  yum: name={{item}} state=present
  with_items:
      - mysql-server
      - MYSQL-python

- name: start mysql 
  service: name=mysqld state=installed
 
- name: copy config
  template: src=hosts.j2 dest=/opt/mysql.cf  owner=root mode=0644 group=root
  notity:
     - restart mysqld
  

  
