---
- name: install httpd
  yum: name={{item}} state=present
  with_items:
      - httpd
      - httpd-devel


#conifg
- name: copy file
  template: src=my.cf.j2 dest=/opt/httpd.cf
  notify:
     - start httpd
#run apache
- name: start apache
  service: name=httpd state=installed


