---
- name: install php
  yum: name={{item}} state=present
  with_items:
      - php
      - php-devel
  

- name: test vars
  debug: msg="user:{{user}}"


- name: copy 
  template: src=php.cf.j2 dest=/opt/my.cf owner=root group=root mode=0644
  notify:
     - test php
